CREATE DATABASE CNPM
CREATE TABLE `cnpm`.`benhnhan` (
  `IDBN` VARCHAR(10) NOT NULL,
  `TENBN` NVARCHAR(50) NOT NULL,
  `NS` DATE NOT NULL,
  `GT` NVARCHAR(5) NOT NULL,
  `SDT` VARCHAR(11) NOT NULL,
  `DC` NVARCHAR(100) NOT NULL,
  PRIMARY KEY (`IDBN`));
CREATE TABLE `cnpm`.`bacsi` (
  `IDBS` VARCHAR(10) NOT NULL,
  `TENBS` NVARCHAR(50) NOT NULL,
  `NS` DATE NOT NULL,
  `GT` NVARCHAR(5) NOT NULL,
  `SDT` VARCHAR(11) NOT NULL,
  `PASSWORD` VARCHAR(20) NOT NULL,
  `AVT` TEXT(100) NULL,
  PRIMARY KEY (`IDBS`));
CREATE TABLE `cnpm`.`thuoc` (
  `IDTHUOC` VARCHAR(10) NOT NULL,
  `TENTHUOC` VARCHAR(50) NOT NULL,
  `MOTA` NVARCHAR(200) NOT NULL,
  `LIEUMAX` INT NOT NULL,
  `LIEUMIN` INT NOT NULL,
  `TSMAX` INT NOT NULL,
  `UNIT` INT NOT NULL,
  PRIMARY KEY (`IDTHUOC`));
CREATE TABLE `cnpm`.`donthuoc` (
  `IDDT` INT NOT NULL AUTO_INCREMENT,
  `IDBN` VARCHAR(10) NOT NULL,
  `IDBS` VARCHAR(10) NOT NULL,
  `NGAYTAO` DATE NOT NULL,
  `TRANGTHAI` NVARCHAR(20) NOT NULL DEFAULT 'Chưa hoàn thành',
  PRIMARY KEY (`IDDT`),
  INDEX `IDBN_idx` (`IDBN` ASC) VISIBLE,
  INDEX `IDBS_idx` (`IDBS` ASC) VISIBLE,
  CONSTRAINT `IDBN`
    FOREIGN KEY (`IDBN`)
    REFERENCES `cnpm`.`benhnhan` (`IDBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IDBS`
    FOREIGN KEY (`IDBS`)
    REFERENCES `cnpm`.`bacsi` (`IDBS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
CREATE TABLE `cnpm`.`ctdonthuoc` (
  `IDDT` INT NOT NULL,
  `IDTHUOC` VARCHAR(10) NOT NULL,
  `LIEULUONG` INT NOT NULL,
  `TS` INT NOT NULL,
  `SL` INT NOT NULL,
  `DANG` NVARCHAR(10) NOT NULL,
  PRIMARY KEY (`IDDT`, `IDTHUOC`),
  INDEX `IDTHUOC_idx` (`IDTHUOC` ASC) VISIBLE,
  CONSTRAINT `IDDT`
    FOREIGN KEY (`IDDT`)
    REFERENCES `cnpm`.`donthuoc` (`IDDT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IDTHUOC`
    FOREIGN KEY (`IDTHUOC`)
    REFERENCES `cnpm`.`thuoc` (`IDTHUOC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);